apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ws
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-ws
  template:
    metadata:
      labels:
        app: demo-ws
    spec:
      containers:
        - name: demo-ws
          image: go-ws:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
