apiVersion: v1
kind: Service
metadata:
  name: demo-ws-svc
spec:
  selector:
    app: demo-ws-svc
  # type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30001
